name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      # Checkout
      - uses: actions/checkout@v2

      # Setup
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org/'

      # Dependencies
      - name: Install Node dependencies
        run: npm ci

      # Build
      - name: Build package
        run: npm run build

      # Tests
      - name: Run Unit tests
        run: npm run test:unit
      - name: Run Package tests 
        run: npm run test:package

      # Publish
      - name: Publish to NPM
        if: github.ref == 'refs/heads/master'
        run: npm publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
